[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Zoom Easy Meetings"
authors = [{name = "Francesco De Angelis 'Engeniero'", email = "engenierpersonal@outlook.com"}]
dynamic = ["version", "description"]
